# Generated by Django 2.2 on 2019-10-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_full', models.IntegerField()),
                ('is_full', models.BooleanField(blank=True, default=False)),
                ('has_leak', models.BooleanField(blank=True, default=False)),
                ('has_overheat', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('map_path', models.CharField(max_length=512)),
                ('bins', models.ManyToManyField(to='trash.Bin')),
            ],
        ),
    ]
