# Generated by Django 2.2 on 2019-10-05 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='percent_full',
            new_name='current_filled',
        ),
        migrations.AddField(
            model_name='bin',
            name='current_temp',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bin',
            name='last_collection',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 15, 41, 55, 584959), null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='next_collection',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 15, 41, 55, 584959)),
        ),
        migrations.AlterField(
            model_name='facility',
            name='bins',
            field=models.ManyToManyField(related_name='facility', to='trash.Bin'),
        ),
    ]
