# Generated by Django 2.2 on 2019-10-05 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0003_auto_20191005_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.CharField(default='123 Null Way', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bin',
            name='last_collection',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 15, 56, 10, 381122), null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='next_collection',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 15, 56, 10, 381122)),
        ),
    ]
