# Generated by Django 2.2 on 2019-10-05 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_auto_20191005_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='last_collection',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 16, 43, 40, 898301), null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='next_collection',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 16, 43, 40, 898301)),
        ),
    ]
