# Generated by Django 2.2 on 2019-10-05 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0005_auto_20191005_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='last_collection',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 17, 35, 20, 455900), null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='next_collection',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 17, 35, 20, 455900)),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
