# Generated by Django 2.2 on 2019-10-06 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0006_auto_20191005_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='last_collection',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 19, 14, 34, 154170), null=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='next_collection',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 19, 14, 34, 154170)),
        ),
    ]
