# Generated by Django 2.2 on 2019-10-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0007_auto_20191005_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bin',
        ),
    ]
